[package]
name = "geometry"
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
indexmap = "2.6.0"
# std = { path = "../std", version = "0.4.0" }
